<?php
$text = [
"La vie ce n'est pas seulement respirer, c'est avoir le souffle coupé. <b>Alfred Hitchcock</b>",
"Le voyageur voit ce qu’il voit, le touriste voit ce qu’il est venu voir. <b>Gilbert Keith Chesterton</b>",
"Le plus beau voyage, c'est celui qu'on n’a pas encore fait. <b>Loïck Peyron</b>",
"Si vous pensez que l'aventure est dangereuse, je vous propose d'essayer la routine. Elle est mortelle. <b>Paulo Coelho</b>",
"Un voyage de 1 000 kilomètres commence toujours par un pas. <b>Lao Tseu</b>",
"Tu ne peux pas voyager sur un chemin sans être toi même le chemin. <b>Bouddha</b>",
"Le véritable voyage de découverte ne consiste pas à chercher de nouveaux paysages, mais à avoir de nouveaux yeux. <b>Marcel Proust</b>",
"On ne va jamais aussi loin que lorsqu'on ne sait pas où l'on va. <b>Christophe Colomb</b>",
"Rester, c’est exister. Voyager, c’est vivre. <b>Gustave Nadaud</b>",
"Les voyages forment la jeunesse. <b>Montaigne</b>",
"Il n'y a d'homme plus complet que celui qui a beaucoup voyagé, qui a changé vingt fois la forme de sa pensée et de sa vie. <b>Alfonse de Lamartine</b>",
"Voyageur, il n'y a pas de chemin, le chemin se fait en marchant. <b>Antonio Machado</b>",
"On voyage pour changer, non de lieu, mais d'idées. <b>Hippolyte Taine</b>",
"Un voyage se passe de motif. Il ne tarde pas à prouver qu'il se suffit à lui-même. On croit qu'on va faire un voyage mais bientôt c'est le voyage qui vous fait ou vous défait. <b>Nicolas Bouvier</b>",
"L’essence de la vie ? Bio-diversifier ses idées sur les chemins du monde et faire voyager ses cinq sens ! <b>Ludovic Lesven</b>",
"Tout voyage est une agression. Il vous contraint à faire confiance à des inconnus et à perdre de vue le confort familier du foyer et des amis, on est en perpétuel déséquilibre. On ne possède rien en dehors de l'essentiell'air, le sommeil, les rêves, la mer, le cieltoutes choses qui tendent à l'éternité ou du moins à ce que nous en imaginons. <b>Cesare Pavese</b>",
"Les grands voyages ont ceci de merveilleux que leur enchantement commence avant le départ même. On ouvre les atlas, on rêve sur les cartes. On répète les noms magnifiques des villes inconnues. <b>Joseph Kessel</b>",
"Voyager c'est naître et mourir à chaque instant. <b>Victor Hugo</b>",
"Courir le monde de toutes les façons possibles, ce n'est pas seulement la découverte des autres, mais c'est d'abord l'exploration de soi-même, l'excitation de se voir agir et réagir. C'est le signe que l'homme moderne a pris conscience du gâchis qu'il y aurait à rendre passive une vie déjà bien courte. <b>Xavier Maniguet</b>",
"L’homme qui veut s’instruire doit lire d’abord, et puis voyager pour rectifier ce qu’il a appris. <b>Giacomo Casanova</b>",
"Notre vie est un voyage constant, de la naissance à la mort. Le paysage change, les gens changent, les besoins se transforment, mais le train continue. La vie, c'est le train, ce n'est pas la gare. <b>Paulo Coelho</b>",
"Qui n'a pas quitté son pays est plein de préjugés . <b>Carlo Goldoni</b>",
"Voyage avec deux sacs, l'un pour donner, l'autre pour recevoir. <b>Johann Wolfgang von Goethe</b>",
"Et il n'est rien de plus beau que l'instant qui précède le voyage, l'instant où l'horizon de demain vient nous rendre visite et nous dire ses promesses. <b>Milan Kundera</b>",
"Quand on ne voyage qu'en passant, on prend les abus pour les lois du pays. <b>Voltaire</b>",
"Le voyage est une espèce de porte par où l’on sort de la réalité comme pour pénétrer dans une réalité inexplorée qui semble un rêve. <b>Guy de Maupassant</b>",
"La vie est un long champ à cultiver. voyager, c’est y semer la diversité de la terre. voyager, c’est l’embellir des couleurs du monde. <b>Ludovic Lesven</b>",
"Lorsqu'elle s'enfuit, la route est la seule amante qui vaille la peine d'être suivie. <b>Sylvain Tesson</b>",
"Il faut voyager pour frotter et limer sa cervelle contre celle d'autrui. <b>Montaigne</b>",
"Le monde est un livre et ceux qui ne voyagent pas n'en lisent qu'une page. <b>Saint Augustin d'Hippone</b>",
"On ne voyage pas pour se garnir d'exotisme et d'anecdotes comme un sapin de Noël, mais pour que la route vous plume, vous rince, vous essore, vous rende comme ces serviettes élimées par les lessives qu'on vous tend avec un éclat de savon dans les bordels. <b>Nicolas Bouvier</b>",
"S'éloigner de tout rapproche un peu de l'essentiel. <b>Loïck Peyron</b>",
"Le voyage c'est aller de soi à soi en passant par les autres. <b>Proverbe Touareg</b>",
"Le bon voyageur n’a pas d’itinéraire et n’a pas l’intention d’arriver. <b>Lao Tseu</b>",
"Voyager rend modeste. On voit mieux la place minuscule que l’on occupe dans le monde. <b>Gustave Flaubert</b>",
"Même le plus long des voyages commence par un premier pas. <b>Lao Tseu</b>",
"Les folies sont les seules choses que l'on ne regrette jamais. <b>Oscar Wilde</b>",
"J'adore voyager, mais je déteste arriver. <b>Albert Einstein</b>",
"Je ne suis pas encore allée partout mais c'est sur ma liste. <b>Susan Sontag</b>",
"Un voyageur ? C'est un homme qui s'en va chercher un bout de conversation au bout du monde. <b>Barbay d'Aurevilly</b>",
"Au premier voyage, on découvre. Au second, on s'enrichit. <b>Proverbe touareg</b>",
"Les voyages sont l'éducation de la jeunesse et l'expérience de la vieillesse. <b>Francis Bacon</b>",
"De tous les livres, celui que je préfère est mon passeport. <b>Alain Borer</b>",
"Comme tout ce qui compte dans la vie, un voyage est une oeuvre d'art. <b>André Suares</b>",
"le voyage c'est aller de soi à soi en passant par les autres. <b>Proverbe touareg</b>",
"La nature n'est pas un endroit à visiter. C'est chez vous. <b>Gary Sinder</b>",
"Le voyageur voit ce qu'il voit, le touriste voit ce qu'il est venu voir. <b>G.K. Chesterton</b>",
"Suivez vos rêves, ils connaissent le chemin. <b>Auteur inconnu</b>",
"Deux routes s'offraient à moi, et là, j'ai suivi celle où l'on n'allait pas, et j'ai compris toute le différence. <b>Robert Frost</b>",
"La vie est un long champ à cultiver. Voyager, c'est y semer la diversité de la Terre. Voyager, c'est l'embellir des couleurs du monde. <b>Ludovic Lesven</b>",
"Le voyageur est celui qui se donne le temps de la rencontre et de l'échange. <b>Frédéric Lecloux</b>",
"Le voyageur voit ce qu'il voit, le touriste voit ce qu'il est venu voir ! <b>Gilbert Keith Chesterton</b>",
"Rester c'est exister : mais voyager, c'est vivre. <b>Gustave Nadaud</b>",
"Chaque voyage est le rêve d'une nouvelle naissance. <b>Jean Royer</b>",
"Le véritable voyage de découverte ne consiste pas à chercher de nouveaux paysages, mais à avoir de nouveaux yeux. <b>Marcel Proust</b>",
"La bonne humeur est un bon compagnon de voyage. <b>Paul de Kock</b>",
"Qui n'a pas quitté son pays est plein de préjugés. <b>Carlo Goldoni</b>",
"L'homme qui veut s'instruire doit lire d'abord, et puis voyager pour rectifier ce qu'il a appris. <b>Giacomo Casanova</b>",
"Lorsqu'elle s'enfuit, la route est la seule amante qui vaille la peine d'être suivie. <b>Sylvain Tesson</b>",
"Un voyage, c'est une folie qui nous obsède, nous emporte dans le mythe. <b>Sylvain Tesson</b>",
"L'impulsion du voyage est l'un des plus encourageants symtômes de la vie. <b>Agnès Repplier</b>",
"Qui voyage ajoute à sa vie ! <b>Proverbe Berbère</b>",
"Le voyage représente une tentative pour transformer un rêve en réalité ! <b>Alain de Botton</b>",
"L'instant le plus heureux d'une vie humaine est le départ vers une terre inconnue. <b>Richard Burton</b>",
"Contre les chagrins de la vie, le voyage n'est-il pas le meilleur remède ? <b>Michel Tournier</b>",
"Quit your job, find a beach, take a risk, fall in love. <b>Auteur inconnu</b>",
"Quand rien n'est prévu, tout est possible. <b>Antoine de Maximy</b>",
"Veux-tu vivre heureux ? Voyage avec deux sacs : un pour donner, l'autre pour recevoir. <b>Johann Wolfang Von Goethe</b>",
"En route, le mieux c'est de se perdre. Lorsqu'on s'égare, les projets font place aux surprises et c'est alors, mais alors seulement, que le voyage commence. <b>Nicolas Bouvier</b>",
"Qui a l'habitude de voyager sait qu'il vient toujours un moment où il faut partir. <b>Paulo Coelho</b>",
"Celui qui a une maison n'en a qu'une. Celui qui n'en a aucune en a mille. <b>Proverbe indien</b>",
"Dans le voyage, il n'y a pas de certitude, seulement de l'aventure. <b>Auteur inconnu</b>",
"Le voyage est la seule chose qu'on achète qui nous rend plus riche. <b>Auteur inconnu</b>",
"Voyager est un triple plaisir : l'attente, l'éblouissement et le souvenir. <b>Ilka Chase</b>",
"Si vous pensez que l’aventure est dangereuse, Essayez la routine… Elle est mortelle ! <b>Paulo Coehlo</b>",
"Au premier voyage on découvre, au second on s'enrichit. <b>Proverbe touareg</b>",
"La vie, ce n'est pas seulement respier, c'est aussi avoir le souffle coupé. <b>Alfred Hitchcock</b>",
"Celui qui voyage sans rencontrer l'autre ne voyage pas, il se déplace. <b>Alexandra David-Neel</b>",
"Rien ne développe l'intelligence comme les voyages. <b>Emile Zola</b>",
"Voyager, c'est partir à la découverte de l'autre. Et le premier inconnu à découvrir, c'est vous. <b>Oliver Föllmi</b>",
"Le monde est un livre, et ceux qui ne voyagent pas n'en lisent qu'une page. <b>Saint-Augustin</b>",
"Cela rend modeste de voyager, on voit quelle petite place on occupe dans le monde. <b>Gustave Flaubert</b>",
"Le véritable voyage ne consiste pas à chercher de nouveaux paysages, mais à avoir de nouveaux yeux. <b>Marcel Proust</b>",
"Tout ce que vous avez à faire, c'est décider de partir. Et le plus dur est fait. <b>Tony Wheeler</b>",
"Quand on marche seul on va vite, mais quand on marche à deux on va plus loin. <b>Proverbe arabe</b>",
"Le voyage est un retour vers l'essentiel. <b>Proverbe tibétain</b>",
"Un voyage se passe de motifs. Il ne tarde pas à prouver qu'il se suffit à lui-même. <b>Nicolas Bouvier</b>",
"On voyage pour changer, non de lieu, mais d'idées. <b>Hippolyte Taine</b>",
"De tous les livres, celui que je préfère est mon passeport. <b>Alain Borer</b>",
"On ne fait pas un voyage. Le voyage nous fait et nous défait, il nous invente. <b>David Le Breton</b>",
"Rester c'est exister, mais voyager c'est vivre. <b>Gustave Nadaud</b>",
"On peut voyager non pour se fuir, chose impossible, mais pour se trouver. <b>Jean Grenie</b>"
];
?>